"""empty message

Revision ID: 012d4fc07647
Revises: bd855ace68e7
Create Date: 2026-08-27 12:01:28.396598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012d4fc07647'
down_revision = 'bd855ace68e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
