"""empty message

Revision ID: 057a63cb1f2a
Revises: f384eba88442
Create Date: 2026-07-16 19:40:28.102863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057a63cb1f2a'
down_revision = 'f384eba88442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('working_on', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.drop_column('working_on')

    # ### end Alembic commands ###
