"""empty message

Revision ID: 0925a0544eba
Revises: fdb49a9bbbcc
Create Date: 2025-11-04 11:02:53.897402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0925a0544eba'
down_revision = 'fdb49a9bbbcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=2000000),
               existing_nullable=True)

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('discount')

    with op.batch_alter_table('pos_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer', sa.String(length=400), nullable=True))

    with op.batch_alter_table('received_item', schema=None) as batch_op:
        batch_op.alter_column('expired_date',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=400),
               existing_nullable=True)
        batch_op.drop_column('batch_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('received_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_number', mysql.VARCHAR(length=500), nullable=True))
        batch_op.alter_column('expired_date',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('pos_payment', schema=None) as batch_op:
        batch_op.drop_column('customer')

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', mysql.VARCHAR(length=400), nullable=True))

    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=sa.String(length=2000000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
