"""empty message

Revision ID: 09cf0a25d209
Revises: 32bc05f305a2
Create Date: 2026-07-30 10:15:43.218125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09cf0a25d209'
down_revision = '32bc05f305a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
