"""empty message

Revision ID: 1bf0d38b00fa
Revises: 41b4e869f194
Create Date: 2026-07-08 16:33:03.889269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf0d38b00fa'
down_revision = '41b4e869f194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('departure_date',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('arrival_date',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('canceld_order', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('order_status',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('waiter',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('event_payment', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('food_chef', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('gop', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('arrival_date',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('id_upload',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('checkout_date',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('waiter',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('paid_status',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('iteman', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('order_status',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('waiter',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('item_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('family',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('payment_date',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('checkin_date',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('checkout_date',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('wifi_code',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('pos_payment', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('payment_date',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('purchase_request', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('received_item', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('refund', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('return_request', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('room_report', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('room_type', schema=None) as batch_op:
        batch_op.alter_column('amenities',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('image_one',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('image_two',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('image_three',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('image_one',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('salary_payment', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('stock_transfer', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('stock_transfer_out', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('stock_usage', schema=None) as batch_op:
        batch_op.alter_column('operation',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('wifi', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wifi', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('stock_usage', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('operation',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('stock_transfer_out', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('stock_transfer', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('salary_payment', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('image_one',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('room_type', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('image_three',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('image_two',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('image_one',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('amenities',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('room_report', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('return_request', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('refund', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('received_item', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('purchase_request', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('pos_payment', schema=None) as batch_op:
        batch_op.alter_column('payment_date',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('wifi_code',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('checkout_date',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('checkin_date',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('payment_date',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.alter_column('family',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('item_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('waiter',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('order_status',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('items',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('iteman', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('paid_status',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('waiter',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.alter_column('checkout_date',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('id_upload',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('photo',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('arrival_date',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('gop', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('food_chef', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('event_payment', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.alter_column('waiter',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('order_status',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('items',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('canceld_order', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('arrival_date',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('departure_date',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
