"""empty message

Revision ID: 1ecaf5ff0f9c
Revises: b4f6b28fad4a
Create Date: 2026-07-07 11:39:33.233370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ecaf5ff0f9c'
down_revision = 'b4f6b28fad4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['customer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
