"""empty message

Revision ID: 2195973ee336
Revises: f0919aaf3c9f
Create Date: 2026-08-15 03:54:28.641263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2195973ee336'
down_revision = 'f0919aaf3c9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_email_key', ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
