"""empty message

Revision ID: 32bc05f305a2
Revises: 057a63cb1f2a
Create Date: 2026-07-22 07:06:21.629854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32bc05f305a2'
down_revision = '057a63cb1f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('working_on_id', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.drop_column('working_on_id')

    # ### end Alembic commands ###
