"""empty message

Revision ID: 333b027b0bc5
Revises: 4364d4f5417c
Create Date: 2025-11-23 12:46:58.374851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '333b027b0bc5'
down_revision = '4364d4f5417c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory', sa.String(length=400), nullable=True))

    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=2000000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=sa.String(length=2000000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('account_group', schema=None) as batch_op:
        batch_op.drop_column('subcategory')

    # ### end Alembic commands ###
