"""empty message

Revision ID: 404f750a8538
Revises: 00fc3758abc8
Create Date: 2026-08-01 13:29:33.006961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404f750a8538'
down_revision = '00fc3758abc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
