"""empty message

Revision ID: 41b4e869f194
Revises: 1ecaf5ff0f9c
Create Date: 2026-07-07 12:23:00.266430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b4e869f194'
down_revision = '1ecaf5ff0f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['customer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
