"""empty message

Revision ID: 4364d4f5417c
Revises: 6dd259e0959a
Create Date: 2025-11-17 08:38:53.088491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4364d4f5417c'
down_revision = '6dd259e0959a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coupon_value', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('coupon_applied', sa.String(length=400), nullable=True))

    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=2000000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=sa.String(length=2000000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('coupon_applied')
        batch_op.drop_column('coupon_value')

    # ### end Alembic commands ###
