"""empty message

Revision ID: 4dc4de2d1f4c
Revises: 841d86210718
Create Date: 2025-10-30 18:17:18.106557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4dc4de2d1f4c'
down_revision = '841d86210718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=2000000),
               existing_nullable=True)

    with op.batch_alter_table('received_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_number', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('received_item', schema=None) as batch_op:
        batch_op.drop_column('batch_number')

    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=sa.String(length=2000000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
