"""empty message

Revision ID: 5e1909263809
Revises: 83c070485864
Create Date: 2026-01-17 10:59:06.230181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e1909263809'
down_revision = '83c070485864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=2000000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=sa.String(length=2000000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
