"""empty message

Revision ID: 63dea75ea673
Revises: 404f750a8538
Create Date: 2026-08-01 14:22:38.788482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63dea75ea673'
down_revision = '404f750a8538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=200000000000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=sa.String(length=200000000000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)

    # ### end Alembic commands ###
