"""empty message

Revision ID: 7252cda23bb1
Revises: e8d19aa597eb
Create Date: 2026-08-02 21:12:21.531848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7252cda23bb1'
down_revision = 'e8d19aa597eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_name', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('attachment_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('attachment_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('attachment_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_attachment', sa.Boolean(), nullable=True))
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('is_attachment')
        batch_op.drop_column('attachment_size')
        batch_op.drop_column('attachment_data')
        batch_op.drop_column('attachment_type')
        batch_op.drop_column('attachment_name')

    # ### end Alembic commands ###
