"""empty message

Revision ID: 841d86210718
Revises: 04e21802b3bb
Create Date: 2025-10-28 15:11:11.838328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '841d86210718'
down_revision = '04e21802b3bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canceld_order', schema=None) as batch_op:
        batch_op.drop_column('cashier')

    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=2000000),
               existing_nullable=True)

    with op.batch_alter_table('received_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expired_date', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('received_item', schema=None) as batch_op:
        batch_op.drop_column('expired_date')

    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=sa.String(length=2000000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('canceld_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cashier', mysql.VARCHAR(length=300), nullable=True))

    # ### end Alembic commands ###
