"""empty message

Revision ID: 8f0836dfaceb
Revises: a1fd61f64f98
Create Date: 2026-07-10 12:03:01.586081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f0836dfaceb'
down_revision = 'a1fd61f64f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.String(length=100), nullable=True))

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('balance')

    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
