"""empty message

Revision ID: 9ebf03fd9ad2
Revises: b33180a4b2c4
Create Date: 2025-11-12 14:51:29.598259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ebf03fd9ad2'
down_revision = 'b33180a4b2c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=2000000),
               existing_nullable=True)

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=200), nullable=True))

    with op.batch_alter_table('pos_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_payment', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=sa.String(length=2000000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
