"""empty message

Revision ID: a69d3a39e61a
Revises: d60ee97fd9a1
Create Date: 2026-07-09 13:06:59.668193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69d3a39e61a'
down_revision = 'd60ee97fd9a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_by', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.drop_column('confirmed_by')

    # ### end Alembic commands ###
