"""empty message

Revision ID: a8ed7a0cf959
Revises: 17a625138d26
Create Date: 2026-01-13 13:15:55.852365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8ed7a0cf959'
down_revision = '17a625138d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.String(length=2000000),
               existing_nullable=True)

    with op.batch_alter_table('iteman', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cocktail_setup', mysql.JSON(), nullable=True))
        batch_op.drop_column('voided')
        batch_op.drop_column('whole_price')
        batch_op.drop_column('is_vip')
        batch_op.drop_column('created_date')
        batch_op.drop_column('family')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iteman', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('created_date', mysql.VARCHAR(length=400), nullable=True))
        batch_op.add_column(sa.Column('is_vip', mysql.VARCHAR(length=400), nullable=True))
        batch_op.add_column(sa.Column('whole_price', mysql.VARCHAR(length=400), nullable=True))
        batch_op.add_column(sa.Column('voided', mysql.VARCHAR(length=400), nullable=True))
        batch_op.drop_column('cocktail_setup')

    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=sa.String(length=2000000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
