"""empty message

Revision ID: bd855ace68e7
Revises: 2fb026c04e30
Create Date: 2026-08-27 11:53:55.811210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd855ace68e7'
down_revision = '2fb026c04e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canceld_order', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('customer',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('event_payment', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('method',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('subcategory',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('food_chef', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=sa.VARCHAR(length=2000000),
               type_=sa.String(length=10000000000),
               existing_nullable=True)
        batch_op.alter_column('onetime',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('contain_food',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('contain_drink',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('contain_digital_printing',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('contain_large_format',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('contain_label',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('contain_dtf',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('dtf_confirm',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('digital_printing_confirm',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('large_format_confirm',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('label_confirm',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('working_on_label',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('working_on_id_label',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('working_on_large_format',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('working_on_id_large_format',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('working_on_dtf',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('working_on_id_dtf',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('working_on_digital_printing',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('working_on_id_digital_printing',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('food_confirm',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('drink_confirm',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('food_confirm_at',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('drink_confirm_at',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('note',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('customer',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('delivered_by',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('working_on',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('working_on_id',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('confirmed_by',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('session',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('cat',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('method',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('discount',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('balance',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('pos_payment', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)
        batch_op.alter_column('cat',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    with op.batch_alter_table('salary_payment', schema=None) as batch_op:
        batch_op.alter_column('employee_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salary_payment', schema=None) as batch_op:
        batch_op.alter_column('employee_name',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('pos_payment', schema=None) as batch_op:
        batch_op.alter_column('cat',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('session',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('discount',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('method',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('cat',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('session',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('session',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('confirmed_by',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('working_on_id',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('working_on',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('delivered_by',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('customer',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('note',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('drink_confirm_at',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('food_confirm_at',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('drink_confirm',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('food_confirm',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('working_on_id_digital_printing',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('working_on_digital_printing',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('working_on_id_dtf',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('working_on_dtf',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('working_on_id_large_format',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('working_on_large_format',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('working_on_id_label',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('working_on_label',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('label_confirm',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('large_format_confirm',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('digital_printing_confirm',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('dtf_confirm',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('contain_dtf',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('contain_label',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('contain_large_format',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('contain_digital_printing',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('contain_drink',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('contain_food',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('onetime',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('items',
               existing_type=sa.String(length=10000000000),
               type_=sa.VARCHAR(length=2000000),
               existing_nullable=True)

    with op.batch_alter_table('food_chef', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('subcategory',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('session',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('event_payment', schema=None) as batch_op:
        batch_op.alter_column('method',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('session',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('customer',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('session',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('canceld_order', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
