"""empty message

Revision ID: c2673c087828
Revises: 521c8329b6d4
Create Date: 2025-05-07 11:07:00.721330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2673c087828'
down_revision = '521c8329b6d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('session')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('departure_date',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('arrival_date',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('food_chef', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.alter_column('arrival_date',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('checkout_date',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('waiter',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('paid_status',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('onetime',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('contain_food',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('contain_drink',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('food_confirm',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('drink_confirm',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=200), nullable=True))
        batch_op.alter_column('cashier',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=300),
               existing_nullable=True)

    with op.batch_alter_table('iteman', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('items',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('order_status',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('waiter',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('item_name',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('family',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('table',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('session',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('payment_date',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('checkin_date',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('checkout_date',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('wifi_code',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('pos_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=200), nullable=True))
        batch_op.alter_column('payment_date',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('method',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('cashier',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('session',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('room_report', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('stock_transfer', schema=None) as batch_op:
        batch_op.drop_column('session')

    with op.batch_alter_table('stock_usage', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_login',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('last_logout',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_logout',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('last_login',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('stock_usage', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('stock_transfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session', mysql.VARCHAR(length=200), nullable=True))

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('room_report', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('pos_payment', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('cashier',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('method',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('payment_date',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('category')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('wifi_code',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('checkout_date',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('checkin_date',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('payment_date',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('table',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('family',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('item_name',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('waiter',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('order_status',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('items',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('iteman', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('cashier',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.drop_column('category')

    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.alter_column('drink_confirm',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('food_confirm',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('contain_drink',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('contain_food',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('onetime',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('paid_status',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('waiter',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('items',
               existing_type=sa.String(length=1000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.alter_column('checkout_date',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('arrival_date',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('food_chef', schema=None) as batch_op:
        batch_op.alter_column('session',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('arrival_date',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('departure_date',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
