"""empty message

Revision ID: c5c2dc3465fa
Revises: b555de699932
Create Date: 2026-09-20 11:43:11.895671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c2dc3465fa'
down_revision = 'b555de699932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_bundle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_size', sa.String(length=2000000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_bundle', schema=None) as batch_op:
        batch_op.drop_column('main_size')

    # ### end Alembic commands ###
