"""empty message

Revision ID: f0919aaf3c9f
Revises: 7252cda23bb1
Create Date: 2026-08-14 13:10:18.900130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0919aaf3c9f'
down_revision = '7252cda23bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('working_on_label', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('working_on_id_label', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('working_on_large_format', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('working_on_id_large_format', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('working_on_dtf', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('working_on_id_dtf', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('working_on_digital_printing', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('working_on_id_digital_printing', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.drop_column('working_on_id_digital_printing')
        batch_op.drop_column('working_on_digital_printing')
        batch_op.drop_column('working_on_id_dtf')
        batch_op.drop_column('working_on_dtf')
        batch_op.drop_column('working_on_id_large_format')
        batch_op.drop_column('working_on_large_format')
        batch_op.drop_column('working_on_id_label')
        batch_op.drop_column('working_on_label')

    # ### end Alembic commands ###
