"""empty message

Revision ID: f384eba88442
Revises: 8f0836dfaceb
Create Date: 2026-07-11 13:39:14.705015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f384eba88442'
down_revision = '8f0836dfaceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('delivered_by', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('delivery_contact', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('delivery_address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('delivery_note', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('delivery_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('held_cart', schema=None) as batch_op:
        batch_op.drop_column('delivery_date')
        batch_op.drop_column('delivery_note')
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('delivery_contact')
        batch_op.drop_column('delivered_by')
        batch_op.drop_column('delivery_status')

    # ### end Alembic commands ###
